spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/cowmjucraft_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: cowmjucraft
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

admin:
  user-id: ${ADMIN_USER_ID:admin}
  password: ${ADMIN_PASSWORD_HASH:$2y$10$bR63tK6Xm9f4UqgMJdeWw.wyCQwBeKx6qlWQ0yxNTonkxijrghjUW}
